### ISSUE TITLE
Allow for layers to have set Z levels.

### ISSUE THREAD

**Issue by TerdyTheTerd** [Keksuccino/FancyMenu#109]
**Describe your idea**
Ability to modify the render order, or z-index, of menu items after they have been added. The current behavior is inconsistent. If I add an image that is a transparent shadow, then add buttons, the buttons will render over the shadow image while editing, but after saving the shadow image will then render over the buttons. When full screening the game, the buttons once again render over the shadow image as intended. 

This is both a bug and a feature request, as it would still be amazing to be able to specify render orders for menu items so users can stack items.

**Does it frustrate you to not already have this feature in the mod?**
I can live without it, but it most certainly limits what can be done without being able to effectively layer screen elements over one another.

**Comment by Keksuccino** [comment]
A feature to change the order of objects in the layout (via editor) is planned, but there will always be problems with the order of vanilla buttons. I can't really change the render order of already existing objects of menus, that's why I added the **layout rendering order** to set a layout to either render in the `background` or `foreground`.

A layout with the `background` rendering order will always be rendered behind all default objects of a menu.
When rendered with the `foreground` order, they will be in front of all default objects.

How to find the rendering order in the layout editor: Rightclick the **empty** editor background -> Renderorder

**Comment by TerdyTheTerd** [comment]
So when in full screen, the shadow image renders behind the buttons.
![image](https://user-images.githubusercontent.com/9743432/101235998-f5174480-3692-11eb-87eb-a8a0f3599fc1.png)

Then when I make the window smaller it renders in front of the buttons
![image](https://user-images.githubusercontent.com/9743432/101236029-34459580-3693-11eb-9adb-3a8793b16dcd.png)

Since I can't set the render order, I can't force it to always render behind. I can still click the buttons that are rendered behind the image though.

**Comment by TerdyTheTerd** [comment]
But I can create separate layouts you mean, the background items on one and the buttons on the other?

**Comment by Keksuccino** [comment]
Yes, you can create separate layouts ^^

But the render behavior in your layout is still weird. Are these buttons vanilla buttons or custom buttons?

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.7.0! Thank you for your suggestion!
