### ISSUE TITLE
Possible caching?

### ISSUE THREAD

**Issue by TerdyTheTerd** [Keksuccino/FancyMenu#18]
This mod is very neat in theory, but fails in practice. After watching a loading screen for 2 minutes, I am then greeted by the animation loading screen, which takes just as long if not longer than the animation itself. Is there no way to cache/store the rendered animation to use instead of loading and rendered the animation from scratch each time?

**Comment by Keksuccino** [comment]
The animation loading screen IS caching the animation, that's its whole point ^^
Loading the animation frames into the memory is necessary, otherwise they couldn't be rendered.

The loading screen shouldn't take too long to load, it's actually quiet fast in my opinion.
If your animations are loading too slow, you probably have too many of them OR one of your animations has too many (high res) frames.
