### ISSUE TITLE
Ability to change settings

### ISSUE THREAD

**Issue by codeman1o1** [Keksuccino/FancyMenu#185]
A button action that allows you to change settings like render distance, fov, graphics etc.

**Comment by Keksuccino** [comment]
This would need a hell lot of maintenance every MC update >.<
Will see if I can implement some settings, but definitely not **all** of them.

**Comment by Keksuccino** [comment]
I decided to not do this, because it's just not worth it. The settings should only be changed in the real settings menu, otherwise it could confuse users and it could create compatibility issues with other mods that aren't built to work with settings changes outside of the settings menu. But thank you very much for your suggestion!
