### ISSUE TITLE
1.8.9 needs an update

### ISSUE THREAD

**Issue by PlazmaKG** [Keksuccino/FancyMenu#216]
**Describe your idea**
Would it be possible to update 1.8.9 to v2.3? I know there's a version of Fancy Menu for 1.8.9 (v1.6), but a lot of features are broken in it, such as the %playername% and %playeruuid% placeholders, among other things.

If you can't, that's ok, there's just a lot of people who play this version

**Comment by Keksuccino** [comment]
No, there aren't a lot of players anymore, or at least they don't use FancyMenu ^^ I dropped support for the 1.8.9 version long ago, because nearly nobody used that version. FM has 7.4M downloads and 1.4K of them is from 1.8.9.. It's just not worth the work, sorry :/ I already maintain 5 different versions of FancyMenu, so it would be too much to maintain a version that's barely used by anyone. I'm very sorry.
