### ISSUE TITLE
Music restarts with each animation loop

### ISSUE THREAD

**Issue by Boolyman** [Keksuccino/FancyMenu#223]
**Describe the bug**
The menu background music restarts each time the background animation (which is only about 5 seconds) loops.

**To Reproduce**
1. Use animation maker to assign background music and an animation to your main menu.
2. Load game.

**Expected behavior**
The song to play all the way through, not restart with each loop.

**Comment by Keksuccino** [comment]
You're describing the normal behavior of animation audios. They are supposed to loop with the animation, because, well, they are animation audios.

What you need is an actual menu background audio. You can add audios to your layout by clicking on **Element -> New -> Audio**. You can manage and delete your audios in **Element -> Manage Audios**.

**Comment by Boolyman** [comment]
Thanks, got it.
