### ISSUE TITLE
Crash with Just Enough Resources

### ISSUE THREAD

**Issue by Kasualix** [Keksuccino/FancyMenu#248]
**Describe the bug**
I was using JER to check all the creature drops, and when I turned to the next page, part of the background image I made using FancyMenu appeared at the creature picture, and my game screen started flashing(but the background image never flashed). After flashing for a while, Not Enough Crashes mod reported the error and game crashed.

**To Reproduce**
As stated above.

**Expected behavior**
Game should not crash and the creature picture should not be part of the background image I made using FancyMenu.

**Crash Log**
https://pastebin.ubuntu.com/p/yMKpwv2C42/
The latest.log shows no relevant information.

**Basic Informations (please complete the following information):**
 - Windows
 - fancymenu_forge_2.6.3_MC_1.16.2-1.16.5
 - Forge 36.2.29
 - Minecraft 1.16.5
 - Active Mods: As written in the crash report

**Comment by Keksuccino** [comment]
I tested it with:

- `fancymenu_forge_2.7.2-1_MC_1.16.2-1.16.5`
- `jei-1.16.5-7.7.1.152`
- `JustEnoughResources-1.16.5-0.12.1.128`
- `konkrete_forge_1.3.3_MC_1.16.2-1.16.5`

and it seems to work absolutely fine now! :) Maybe it got accidentally fixed in an update of either JER or FM or it was related to more than just the combination of JER and FM.

Another thing I've noticed is you're using `/_MixinBootstrap-1.1.0.jar mixinbootstrap TRANSFORMATIONSERVICE ` in MC 1.16.5, which is not needed, since 1.16.5 has built-in Mixin. You should remove this.

Will close this for now. If it still crashes when using the mod versions mentioned above and after removing MixinBootstrap, please tell me.
