### ISSUE TITLE
HEX color support for button labels

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#298]

**Comment by Keksuccino** [comment]
- Text elements now support HEX colors

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!

**Comment by caelaThinx** [comment]
![Image](https://github.com/user-attachments/assets/db09e21b-f4dd-4c7e-87bb-291966e690ad)

I cannot find any option to change button label colors _(other than through text formatting within the element that is not perfect and does not allow for the removal of shadows and then requires you to rewrite the button label so it can't be done in bulk)_, meaning that if I want to use a light button texture then **I am screwed** because I would either have no contrast or have to manually create text elements over the buttons and remove the vanilla label. I do not want to use a dark background because that ruins the vibe in my project to bring true OreUI to java edition.

I understand that with changing this you would have to change some vanilla code but I reckon it's worth it and things have changed since you said that 2+ years ago. I request a **reopen** of this request.

**Comment by seriousfreezing** [comment]
Yes, it seems that there will never be a way to remove the shadows from the button text. You can only change their color one by one. :/

**Comment by seriousfreezing** [comment]
How?
