### ISSUE TITLE
Better audio handling for animations (update to new audio system)

### ISSUE THREAD

**Issue by VL4DST3R** [Keksuccino/FancyMenu#320]
**Describe the bug**
So I'm mostly interested in fixing this for the cave animation background, which i reckon is what most people install this mod for anyway. 

Before opening this bug report I've also read past closed tickets relating to sound and learned that the audio is linked to the master slider (bad idea imo) instead of having its own channel or at the very least have it linked to something more reasonable like music. 

Regardless though, the main problem is that as it is now, it is very difficult to get a good audio level at least for this particular scenario, due to the way the volume is linked to the master volume slider. The audio curve itself seems to go almost muted when only at about 50% master volume and absolutely blast your ears at 100%. It seems to go way above/below all the other sounds in the game, which makes finding a volume that's reasonable for both menu and gameplay very difficult.

I actually kinda fixed this myself by lowering the volume of the audio file by a few db with ffmpeg and attached it [here](https://github.com/Keksuccino/FancyMenu/files/9049076/audio.zip) if anyone needs it, but i figured this should be at least mentioned as a standalone issue that should be addressed.

**To Reproduce**
1. Setup Cave Animation as per instructions
2. Set master volume at 100%
3. Toggle Customization ON/OFF to cause it to replay the animation audio
4. Notice blood coming from your ears
5. Set master volume at 50%
6. Redo step 3 and brace for impact

7. Wonder if you have gone deaf from the previous playback as now you can't hear anything

**Expected behavior**
I understand you feel it's too difficult to implement a proper standalone volume slider for it, and I'm not picky, i just want a god dang audio cue that works properly! Be it via a proper separate volume slider, having it linked to something that's *not* most commonly set at 100% (at least in my case), or at the _very_ least having it mapped like all the other sounds in the game instead of how it is now (presumably linearly instead of logarithmic?).

**Crash Log**
N/A

**Screenshots**
N/A

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 2.9.1
 - FabricLoader Version 0.14.8 w/ FabricAPI 0.57.0
 - Minecraft Version 1.19
 - Active Mods: about 116 on a good day, i doubt it's a factor though.
 I do have audio-related mods like Ambient Sounds, Presence Footsteps, Sound Phyisics if it makes a difference.

**Comment by Keksuccino** [comment]
> which i reckon is what most people install this mod for anyway

Not it absolutely isn't. The cave animation has 12k downloads and FancyMenu has 15 million.

> I understand you feel it's too difficult to implement a proper standalone volume slider for it

I don't think that's too difficult, it's just that the audio system used by animations is like 2+ years old and was one of the first things that made it into the mod. That's why it is kinda limited. Most audio stuff already has a new audio system, but updating animations to use that new audio system doesn't have a high priority for me atm, because like 1 out of 10 people use animations for their menus. And 60% of these guys don't even use the animation audio, because they just want short looped animations as background.

-------------

I will maybe update the animation audio system at some point, but it's also possible that I just completely remove it at some point, because video support is currently in the works, which would be the much better alternative to animations with audio.

**Comment by Keksuccino** [comment]
Animations are gone in FancyMenu v3 (replaced by APNGs), so I'm closing this.
