### ISSUE TITLE
[1.18.2] custom menu set on global layout keeps restarting 

### ISSUE THREAD

**Issue by Saereth** [Keksuccino/FancyMenu#388]
**Describe the bug**
when you go to change the keybind settings the "main menu music" seems to abruptly stop, upon exiting out of changing keybinds the music is restarted from the beginning

also when you create a new world it seems the song starts and restarts and restarts and restarts rather than continually playing or not playing at all

**To Reproduce**
Steps to reproduce the behavior (e.g.):
open "change keybinds" and exiting, "create new world" seems to also cause it to occur, unsure about joining an already made world

**Expected behavior**
[A clear and detailed description of what you expected to happen.](keybinds: the song to carry on or "remember" here it is. joining world: either carry on playing or not play at all)

**Basic Informations (please complete the following information):**
 - FancyMenu Version [fancymenu_forge_2.12.2_MC_1.18.2]
 - Forge/Fabric Version [41.0.80]
 - Minecraft Version [e.g. 1.18.2]

**Comment by Keksuccino** [comment]
This sounds like customizations aren't enabled for the keybind/controls screen. Check if customnizations are enabled by clicking on **Current Menu** in the menu bar at the top of every menu.

**Comment by Keksuccino** [comment]
**UPDATE:**

This is **not** a bug in FancyMenu, but in the modpack.

The modpack dev forgot to enable customizations for the menus the music is stopping in.

I started the modpack and tried to enable all menus they forgot.
It should work in almost every menu know, except of the resourepack menu, because that one doesn't like to get customized (I need to fix that already ehem).

You can fix this by yourself by simply replacing the `config/fancymenu/customizablemenus.txt` file with that one:
[customizablemenus.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9796097/customizablemenus.txt)

Will close this issue now, but feel free to open a new one if you have more questions/issues! :)
