### ISSUE TITLE
IMPORTANT: Latest MC Launcher Update killed FM on CurseForge Launcher

### ISSUE THREAD

**Issue by VirtualGaming1** [Keksuccino/FancyMenu#438]
This is just a warning that if you are using this mod and just found out your layouts dose not work it is the minecraft launcher it self that had an update today. For me it was working fine yesterday and today it was not loading my custom layouts and did some reasearch and now it made new config and log file to where your modloader file is at.

**Comment by VirtualGaming1** [comment]
There is a fix for curseforge side and here is a screenshot for the fix.

![image](https://user-images.githubusercontent.com/20447403/200431574-d94ad791-9c2a-4dc8-9329-3461418dac82.png)

you may have same issue with other modlauncher

**Comment by Drflash55** [comment]
Repairing the installation brought back the custom menu screen that was for Pixelmon.
This really did help out a lot.

**Comment by VirtualGaming1** [comment]
that is great to know. this is for sure due to the todays minecraft launcher update and found out you need to do that everytime you want to open up the launcher. Minecraft is having issue with there athocate server guessing of us have to keep on logging in to minecraft launcher.

**Comment by Keksuccino** [comment]
I hope they manage to fix it soon.

Well, I have a fixed 1.19 private build, but it needs **70** changes in my code to fix it, so I will wait just a _tiny_ bit longer before I port these frickin 70 changes to all branches :D

**Comment by VirtualGaming1** [comment]
What all the changes they did on the launcher side?

**Comment by Keksuccino** [comment]
They messed something up with the instance handling, so stuff gets saved to wrong places in some cases.

Here's what I posted in my Discord earlier:

btw, for anyone interested, I found what exactly is causing the CF launcher issue and why it only happens to _some_, but not all files saved to the instance folder.

Normally, when working with files in mod code, you can refer to files in the instance folder by simply shorten paths to `/<stuff inside instance folder>`. So `/config/fancymeny/` is basically something like `C:/stuff/user/.minecraft/config/fancymenu`.

This doesn't work anymore, so now you have to use the reference to the game directory in the `Minecraft` class (`Minecraft#gameDirectory`). This will make it work again, so files get saved to the _real_ instance again, etc.

That's why FancyMenu is affected by it. I'm using this basically everywhere..

**Comment by VirtualGaming1** [comment]
is there any fix that curse forge should try to fix? what I noticed is that they use java agu

**Comment by Kasax007** [comment]
For anyone who also has this issue on their clients and is looking for a better solution than to always running the cf fix, I have heard that the GD launcher doesn't have this issue and allows you to play like normal. Might be a temporary fix.

**Comment by Keksuccino** [comment]
So, just in case you haven't noticed already: **Everything works again!** The CurseForge launcher got an update and I think even MC reverted their launcher changes, so FancyMenu, Drippy and all of my other mods are working again!

Let's just hope it never happens again, because I aged like 5 years in the last 24 hours.
