### ISSUE TITLE
Incompability with Flash's Npc

### ISSUE THREAD

**Issue by GONGON205** [Keksuccino/FancyMenu#443]
**Describe the issue**
When I create an entity player with this mod installed it automatically crashes but If i removed it it works perfectly.

**Game Log**
[latest.log](https://github.com/Keksuccino/FancyMenu/files/10005842/latest.log)

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 2.12.6
 - Forge/Fabric Version Forge 40.1.84
 - Minecraft Version 1.18.2
 - Active Mods 181 mods

**Comment by Keksuccino** [comment]
Seems like this was caused by FancyMenu's old Player Entity element.
Please update your FancyMenu to the latest version, delete all old Player Entity elements and add them again (this adds the new, reworked Player Entity element). This should fix the issue, but if it still happens, please open a new issue, thank you very much!
