### ISSUE TITLE
Background is partially transparent

### ISSUE THREAD

**Issue by dmohr2** [Keksuccino/FancyMenu#444]
**Describe the bug**
When exiting the FancyMenu config mode, the background image becomes semi-transparent, showing the default dirt background behind it.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Add a background image
2. Save the layout
3. Exit the editor (Ctrl+Alt+C)

**Expected behavior**
The background image appears the same way it did in the editor.

**Game Log**
N/A

**Screenshots**
If screenshots would help to explain the issue, please include these.
![image](https://user-images.githubusercontent.com/93624029/202194292-3c58bcf7-5d09-4082-880e-f2b211df2c88.png)
![image](https://user-images.githubusercontent.com/93624029/202194359-f16344e1-dbb6-4eb0-ba3d-7352cd34ff28.png)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version: 2.12.9
 - Forge/Fabric Version: Forge 40.1.85
 - Minecraft Version: 1.18.2
 - Active Mods: WaffleMods 3 Modpack (https://www.curseforge.com/minecraft/modpacks/wafflemods-3)

**Comment by cilcoOf** [comment]
I don't know why dmohr closed this issue, but seems like the issue is still present.
![image](https://user-images.githubusercontent.com/111222469/218297202-d5150ded-889a-4b04-9c29-de9d09993280.png)
![image](https://user-images.githubusercontent.com/111222469/218297209-c16d76d3-dc52-43dd-b11d-df318f8e7453.png)

modlist: 

https://pastebin.com/nKjzayZS

**Comment by Keksuccino** [comment]
It's a mod conflict with EnhancedVisuals.

http://fm.keksuccino.com/en/incompatibility-list
