### ISSUE TITLE
Applied mixin for ``GuiScreen`` way too early, causing mixin incompatibility.

### ISSUE THREAD

**Issue by GBLodb** [Keksuccino/FancyMenu#475]
**Describe the issue**
FancyMenu loaded ``net.minecraft.client.gui.GuiScreen`` too early, causing mixin incompatibility with CustomSkinLoader(https://github.com/xfl03/MCCustomSkinLoader).

**Game Log**
[latest.log](https://pastebin.mozilla.org/ZXkJd7Jp)

**Basic Informations:**
 - OS: Windows 10 Professional 222H (Windows Feature Experience Pack 120.2212.4190.0)
 - FancyMenu Version: forge_2.13.1_MC_1.12-1.12.2
 - Forge/Fabric Version: 14.23.5.2860
 - Minecraft Version: 1.12.2
 - Active Mods: MixinBooter(7.0), CustomSkinLoader(ForgeLegacy-14.15-SNAPSHOT-355)

**Comment by Keksuccino** [comment]
It's not FancyMenu that's loading classes too early, but a core mod.
Mixin fails to inject FancyMenu's mixins because the trarget class got loaded already (by a core mod).

At least that's what's happening in your log, because I wasn't able to reproduce this. Both mods work just fine for me using MixinBoostrap (instead of MixinBooter).

I can't fix this since it's just one of the many mixin + core mod incompatibilities, sorry.
