### ISSUE TITLE
[suggestion] animation repository that allows installation from inside the game

### ISSUE THREAD

**Issue by yukinagatosc2** [Keksuccino/FancyMenu#51]
Currently animations are manually downloaded and installed but what if there was a repository of animations and other content that the mod could download from and install with just a few clicks instead?  It would also make setting a default animation much easier for mod packs as all you would have to do is set the desired animation in the config/gui which would automatically download the animation if it isn't already present in the install.

**Comment by Keksuccino** [comment]
Automatically download things like animations would take too much time, because the game can’t start before the animation is completely downloaded (to be able to load the animation on start). But you are able to add a button and run a button script when clicking it that downloads the animation, opens a message that tells you the download is completed and that you need to restart the game to apply it. That’s the best way to do it. Adding a repo system would be too much work and would cause too much trouble, I’m very sorry.
