### ISSUE TITLE
The new splash screen system for forge is marginally incompatible

### ISSUE THREAD

**Issue by cpw** [Keksuccino/FancyMenu#571]
**Describe the issue**
What exactly is telling you that the mod is incompatible?
Me. I wrote the new forge splash screen code. Your mixins are targetting something that no longer exists.

**Game Log**
None. It's not crashing.

**Screenshots**
Try using 47.0.4 or higher of forge. Things don't quite work. Also, I think the new interstitial "configure narrator" screen also interferes with your stuff, so it's probably time to slightly rethink a bit?

The new overlay system should be able to support your usecase, probably without deep mixin hacks as well. Let's review needs for event hooks.

Edit: I suggest that if you want to explore ways to make your life easier, ping me (cpw) in the forge discord.

**Comment by Keksuccino** [comment]
Hi!

> Your mixins are targetting something that no longer exists

Thank you for telling me! Will release a fix asap! :)

> so it's probably time to slightly rethink a bit?

Yeah, you're right. Some of FancyMenu's code is also ancient and is just not good enought anymore tbh. That's why I'm currently working on FancyMenu v3, which is basically a full rewrite, so I'm already rethinking a lot of stuff lately :D

> Let's review needs for event hooks

Well, that's very nice of you and I really appriciate it, but v3 will be a MultiLoader setup (Forge/Fabric), so I try to not use loader-dependand stuff very often.. I know you probably don't like that idea, but even though I try to avoid it, I still use events where it's really important for stability (like registry stuff, etc.), so don't worry.

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.14.8 for Forge 1.20.1!
