### ISSUE TITLE
Incompatibility with "ukulib"

### ISSUE THREAD

**Issue by Capysussa** [Keksuccino/FancyMenu#690]
When having customized the options menu (pretty sure it doesn't matter how), and then upon opening said menu, the game abruptly crashes.

1. Customize options menu
2. Opening the menu, after re-opening the game, or in game
3. Game Crashes

The Game does not crash.

[latest.log](https://github.com/Keksuccino/FancyMenu/files/14229688/latest.log)

OS: Windows 10 Home
FancyMenu Version: 3.0.6
Fabric Version: 0.15.3
MC Version: 1.20.4
Active Mods: (All Mods in this Folder are active)
https://www.mediafire.com/file/4gliap1jq0475md/Mods.zip/file

**Comment by Keksuccino** [comment]
`at net.minecraft.class_1043.handler$eae000$modernfix$storeCloseTrace(class_1043.java:1030) ~[client-intermediary.jar:?]`

Try to remove "Modern Fix". If that doesn't fix the issue, please start the game with only FancyMenu + dependencies installed.

**Comment by Capysussa** [comment]
Thanks! That fixed the issue.

**Comment by Keksuccino** [comment]
Some notes:

- Seems like it's not related to ModernFix (could be ukulib, but not 100% sure, maybe it's a combination of a performance mod and ukulib)
- `class_429` = `OptionsScreen`
- `class_1043` = `DynamicTexture`
- `Cannot invoke "NativeImage#getWidth()" because "DynamicTexture#pixels" is null`
- ukulib places a Mixin in `OptionsScreen` (`class_429.md8c356a$ukulib$lambda$registerHeadTex$2$1`) that registers some texture, but that fails because of a NullPointer

**Comment by Keksuccino** [comment]
Fixed on ukulib's side in ukulib v1.1.2!
