### ISSUE TITLE
Incompatibility with "Suggestions API"

### ISSUE THREAD

**Issue by Liamgrayskull** [Keksuccino/FancyMenu#691]
With latest 1.20.1 version of both Ad Astra, Fancy Menu & all necessary dependencies, game crashes with this error 

**To Reproduce**
Install all forge versions of mods & their dependencies
place & fuel a rocket
fly out of atmosphere, crash upon screen load

**Expected behavior**
Space location selection screen to generate

https://gist.github.com/Liamgrayskull/817ed6ac0b26d6884821226aace0a7f2

https://gist.github.com/Liamgrayskull/faa59d39f16f57dd5de0f9c54f4c8300

 - Windows
 - FancyMenu v3.0.6
 - Forge w/ Sinytra Connector
 - 1.20.1
 - Forge versions of all related mods

**Comment by Keksuccino** [comment]
I don't see how FancyMenu could cause this.

Looks like the error starts in `io.github.aratakileo.suggestionsapi`.
Would be best to report this to the "Suggestions API" dev, because I really don't know what I do that could cause this. I only have accessor Mixins in `EditBox` and `CommandSuggestions`.

Or did you enable customizations for some special Ad Astra screen or something? In that case try to use the "Kill-Switch Customizations" option of the "Customization" menu bar tab while in the Title Screen. This disables customizations for all screens.

**Comment by Liamgrayskull** [comment]
Looks like it was a false alarm on FancyMenu's end, sorry if that ended up misleading- it seems suggestionAPI has been the root of a number of prevalent things I've been debugging lately, I'll see about getting some reports to them. Thank you for your time!
