### ISSUE TITLE
Crash w/ OptiFine

### ISSUE THREAD

**Issue by WenXin20** [Keksuccino/FancyMenu#7]
**Describe the bug**
The game crashes as soon as the menu animation (Example Animation) tries to play. The crash seems to happen when OptiFine Pre12 is installed, which requires OptiForge to work with Forge, which in turn requires Mixin Bootstrap to function.

**To Reproduce**
1. Launch the game
2. Install all required mods
3. Crash...

**Expected behavior**
No crash

[Crash Report](https://gist.github.com/WenXin20/7df83f07403ee7f9294f692543b6202c)

**Basic Informations (please complete the following information):**
 - OS: `Windows 10`
 - `FancyMenu v0.4.3`
 - `Forge v31.1.30`
 - `Minecraft v1.15.2`
 - [`OptiFine vHD U G1 pre12`](https://optifine.net/downloads)
 - [`OptiForge v0.1.6`](https://www.curseforge.com/minecraft/mc-mods/optiforge)
 - [`Mixin Bootstrap v1.0.2`](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap)

**Comment by Keksuccino** [comment]
OptiForge is an unofficial mod to make the 1.15 Optifine builds compatible with Forge.
Optifine needs to add Forge support by itself. If it is still crashing in the first stable Optifine build for 1.15, I will try to fix the issue. I don’t think I can fix it now, because OptiForge seems to manipulate Forge on bytecode level to make Optifine compatible with it.

**Comment by WenXin20** [comment]
The previous version, v0.4.2, works just fine with Optifine though, so something in the newest version broke compat.

**Comment by Keksuccino** [comment]
Yes, it was my fault. I've fixed it, hotfix is coming soon!

**Comment by WenXin20** [comment]
Thanks!

**Comment by Keksuccino** [comment]
FancyMenu v0.4.3.1 is now released and should hopefully fix the problem.
