### ISSUE TITLE
Crash with mod 'Trade Uses'

### ISSUE THREAD

**Issue by stlouisn** [Keksuccino/FancyMenu#711]
**Describe the issue**
While interacting with villager (trade menu open), game crashes as soon as you hover over villager offered trades when both 'fancymenu' and 'trade uses' are installed. Reverted to latest fancymenu version 2 (2.14.13) and fault cleared. Problem only occurs with latest v3.x.

**Game Log**
https://mclo.gs/aKlWyQn

**Basic Informations (please complete the following information):**
 - Minecraft 1.20.1
 - Forge 47.2.20
 - fancymenu_forge_3.1.0_MC_1.20.1
 - tradeuses-1.2.2-1.20.x-FORGE

**Comment by Khajiitos** [comment]
It's interesting that this mod messes with the trade menu as well. I will investigate this issue later - I'm not fully certain if what I'm looking at is the problem, but from the looks of it this, the crash occurs in my code due to a slight programming mistake, which just happened to never crash without other mods that play with that menu.  
![image](https://github.com/Keksuccino/FancyMenu/assets/58109276/682c8c9a-116d-49a0-ae9a-4f8dfdcdde89)

**Comment by stlouisn** [comment]
Thank you for the quick fix. I can confirm this is fixed with Trade Uses version 1.2.4. Love both of your mods btw.
