### ISSUE TITLE
Player entity scaled too much goes through background

### ISSUE THREAD

**Issue by Mowzy-Graphics** [Keksuccino/FancyMenu#746]
**Describe the bug**
When a player entity is scaled too much on a menu, the entity will go through the background when looking at cursor above it
(screenshots will probably be more helpful to understand the issue)

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Add a player entity to a menu
2. Scale it up. I've used `130` in the screenshots provided
3. Place your mouse over the character so that he looks up 
4. The character will go through the background _(werther there is an image or not)_

**Expected behavior**
Should probably not hop into another dimension when practicing Limbo

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/39197092/6ab7c95b-016d-435e-ac98-2bc543db10c5)
![image](https://github.com/Keksuccino/FancyMenu/assets/39197092/3892b45a-2a68-461b-8c9e-e7ba10854631)

**Basic Informations (please complete the following information):**
 - OS: [Windows]
 - FancyMenu Version [3.1.2]
 - Forge Version [47.2.20]
 - Minecraft Version [1.20.1]

**Comment by Keksuccino** [comment]
I don't think I can fix that, sorry. At least I don't really know how, because the only thing that makes this slighly better is moving the entity up on its Z axis, but I already did that and I think I can't really move it higher (at least I remember it like that), because it is not rendering anymore/out of the visible area when I move it higher.

Will close this for now.
