### ISSUE TITLE
Make %appdata% work with paths

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#788]
At the moment, I am making windows within minecraft, and I want to copy the wallpaper image from tgjea/AppData/Roaming, this only works for me because it is my vomputer username and I forgot to do the whole path but its also my main drive so if I had it on my D: drive it aint gon' work.

**Comment by Keksuccino** [comment]
I am pretty sure the exact same issue already exists, but I can't find it right now. The other one should be closed and I think I said there that I will not add support for that, because there's no reason to access system directories in FancyMenu. You are supposed to stay in `/config/fancymenu/assets/` or at least the root directory of the MC instance. Sorry, but will not add that.

**Comment by KaaayKaay** [comment]
> I am pretty sure the exact same issue already exists, but I can't find it right now. The other one should be closed and I think I said there that I will not add support for that, because there's no reason to access system directories in FancyMenu. You are supposed to stay in `/config/fancymenu/assets/` or at least the root directory of the MC instance. Sorry, but will not add that.

Is there any way you could add a way to access the .minecraft folder
