### ISSUE TITLE
if it's possible to add a feature to modify the game dirt background？

### ISSUE THREAD

**Issue by A0000Xz** [Keksuccino/FancyMenu#797]
**Describe your idea**
A detailed and clear description of what you want to see in the mod.
The feature should fit the mod's lore. Stuff like "add speaking potatos ridden by Trump" will be ignored.
I couldn't find any tutorial in FancyMenu's wiki about directly replacing the dirt background with other block textures in a one-click manner, so I came to ask.
This has been attempted by some, but unfortunately, the compatibility isn't great. For instance, YUNG's Menu Tweaks Mod can't modify certain areas' dirt backgrounds when coexisting with FancyMenuV3.
And regarding Modmenu Mod, Yung's mod also couldn't achieve modifying the background of the Mod configuration screen.
So, I feel like this feature should be directly integrated into FancyMenu, right?
plz.

**Comment by Keksuccino** [comment]
Yes, with a resource pack. I will not add a feature to replace this texture per-menu, sorry.
If mods have uncustomizable menus, please report this to the author of the other mod, because it's almost never on FM's side. Mods need to make their menus in a Vanilla-like way for FancyMenu to be able to customize them.
