### ISSUE TITLE
Animated background playing only once (loop = true)

### ISSUE THREAD

**Issue by Krampus69** [Keksuccino/FancyMenu#814]
Hello ! 

I made a video for the background of my incoming modpack menu but it has issues.
First issue : The animation is very slow on first play, when I reload the custom menu, it is working properly (60 fps)
Second issue : It doesn't loop. My animation.properties file has this config : 

type = animation

animation-meta {
  name = cave
  fps = 60
  loop = true
  replayintro = false
  namespace = cave

**Expected behavior**
Background animation should loop and be played in 60 fps

**Game Log**
Here is my latest.log file : https://gist.github.com/Krampus69/3da7d48f65d8ac7de4e0de2191b06dff

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] Windows 10 
 - FancyMenu Version [e.g. 0.2]fancymenu_forge_2.14.9_MC_1.16.2-1.16.5
 - Forge/Fabric Version [e.g. 31.2.24] 36.2.39
 - Minecraft Version [e.g. 1.15.1] 1.16.5
 - Active Mods [e.g. Optifine, 5zig, TooManyItems] Here is a full list of my mods : https://gist.github.com/Krampus69/9d06c128ff6c191f9f0a5c3febd3631f

I made a video to show you the issue. It will be much easier to clarify with this : 
https://streamable.com/fdrk03
You can witness on the video that the framerate is very low on the first scene load (from 00:00 to 00:34), and it doesn't loop when the sequence ends (00:35). When I reload the menu by disabling/enabling FancyMenu customisation, the sequence has the right framerate but still doesn't loop.

**Comment by Keksuccino** [comment]
For support, please join the Discord: #569 

You are using MC 1.16.5, which I do not support anymore, that's why you only have access to FancyMenu v2, which had some problems. I am not sure if the problem you described is a bug or something else, but:

- The animation being slow on first run is normal, because you probably don't pre-load animations and if you do, your system or MC setup could have performance issues and that's why the animation can't register its frames fast enough, which makes it run slow the first time
- The video looks like the loop issue is a bug, but it could also be caused by mods like OptiFine and other [incompatible mods](https://fm.keksuccino.dev/en/incompatibility-list)

**I will close and lock this issue for now, because I don't give support here, but if you still have questions, please join the Discord server. Take a look at the issue I mentioned earlier for a link to the server. Thank you very much.
