### ISSUE TITLE
[Question] Can I add a box that shows a panorama

### ISSUE THREAD

**Issue by ZaneDragonBorn** [Keksuccino/FancyMenu#85]
I'm wanting my Background to be dirt and want a box that would show a panorama but am unsure if that's supported. Whether a video or panorama would it be possible to import it as a small box. Also maybe one that will fade out?

**Comment by Keksuccino** [comment]
What exactly do you want to do? Do you want to add a panorama image as small image at a specific position of your menu or do you want to have a panorama image as background?

**Comment by ZaneDragonBorn** [comment]
I'm wanting to have a box or square that contains the panorama. So yes small panorama images that animate

**Comment by Keksuccino** [comment]
~ talked via discord, comment is just a note for me ~

- Feature to set 6-image-panoramas (used by MC) as menu background via customization action will be added in a future update
- Feature to add small 6-image-panoramas as animation-like object to menus will not be added, because it would be too much work

**Comment by Keksuccino** [comment]
Support for 6-image panoramas added in FancyMenu v1.6.0! Thank you for your suggestion!
