### ISSUE TITLE
[1.20.1] Game crashes when trying to customize the pause menu

### ISSUE THREAD

**Issue by vizthex123** [Keksuccino/FancyMenu#907]
**Describe the bug**
As the title says, I tried editing the pause menu and the game crashed.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Edit the pause menu

**Expected behavior**
Being able to edit the pause menu.

**Game Log**
https://gist.github.com/vizthex123/1b61fa19c336b785afdac1597dad0dc2

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: 3.2.3
 - Forge/Fabric Version: Forge 47.3.5
 - Minecraft Version: 1.20.1
 - Active Mod: My [new modpack](https://www.curseforge.com/minecraft/modpacks/hi-tech-revolution), containing 256 mods.

**Comment by corbinpenguin** [comment]
This is happening to me as well... here's my crash log for the instance, as well as a list of the installed mods.
aside from that, I am on Windows 11 and Forge 47.3.0
Hopefully a fix for this is found... I'd like to move the _just zoom_ mod's options button, since the _tips_ mods tips are covering it.
if a fix isn't found i'll likely just uninstall _tips_

[crash-2024-07-22_23.14.12-client.txt](https://github.com/user-attachments/files/16344053/crash-2024-07-22_23.14.12-client.txt)
[mods list.pdf](https://github.com/user-attachments/files/16344069/mods.list.pdf)

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!

**Comment by vizthex123** [comment]
noice, thanks.
