### ISSUE TITLE
Incompatibility with ModernUI (custom GUIs don’t render blur background)

### ISSUE THREAD

**Issue by BredyAK** [Keksuccino/FancyMenu#971]
**Describe the bug**
i find an issue with FancyMenu and ModernUI. ModernUI has a feature which could add a blur effect to screen's background, but it could not add the effect to FancyMenu's custom guis. i reported this issue to ModernUI, but the author said it's FancyMenu's problem, because FancyMenu's custom guis do not have a background. could i ask you for a fix for this? i think you could add a background to FancyMenu's custom guis so that ModernUI could apply the blur effect to them.

also, ModernUI's author believes that FancyMenu removed the Vanilla background, it's a gray color translucent overlay.
and i also check that myself, and find it's true, fancymenu doesn't use a vanilla background in custom guis.

**Expected behavior**
add a vanilla translucent background to custom guis.

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 3.3.2
 - Forge/Fabric Version 47.3.0
 - Minecraft Version 1.20.1
 - Active Mods FancyMenu and its dependences

**Comment by Keksuccino** [comment]
I do not remove the background from Custom GUIs.
Of course they have a background, otherwise there would be nothing behind them.

the incompatibility with ModernUI probably comes from me overriding the `renderBackground()` method for custom GUIs, but I need to do that to be able to control if it should render background stuff or not, depending on the GUI's settings.

I am pretty sure I can’t fix that and you will need to live with it, sorry.

Here is the custom GUI base class. I only override the background render method, but that’s probably where ModernUI places its blur render logic:

https://github.com/Keksuccino/FancyMenu/blob/v3-1.20.1/common/src/main/java/de/keksuccino/fancymenu/customization/customgui/CustomGuiBaseScreen.java

Again: I need to override this method, so I can't really fix that.

**Comment by Keksuccino** [comment]
Will close this, because I can’t fix it on my end and the incompatibility is not too bad. Both mods work fine together, it’s just a small visual bug.
